# Generated by Django 3.0.6 on 2020-05-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comapny_name', models.CharField(max_length=50)),
                ('Realtionship_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Survey_name', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Score', models.BigIntegerField(max_length=2)),
                ('Created_date', models.DateTimeField(blank=True)),
                ('updated_date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
